function createfigureCongruency(X1, YMatrix1, X2, YMatrix2)
%CREATEFIGURE(X1, YMatrix1, X2, YMatrix2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 17-Jan-2019 15:15:26

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'DisplayName','Low','MarkerSize',15,...
    'LineStyle','none',...
    'Parent',axes1);
set(plot1(1),'Marker','o','LineWidth',3,'Color',[1 0 0]);
set(plot1(2),'Marker','v','Color',[1 0.074509803921569 0.650980392156863]);
set(plot1(3),'Marker','+',...
    'Color',[0.490196078431373 0.180392156862745 0.56078431372549]);
set(plot1(4),'Marker','^','Color',[1 0.074509803921569 0.650980392156863]);

% Create multiple lines using matrix input to plot
plot2 = plot(X2,YMatrix2,'DisplayName','High','MarkerSize',15,...
    'LineStyle','none',...
    'Parent',axes1);
set(plot2(1),'Marker','*','LineWidth',5,'Color',[0 1 1]);
set(plot2(2),'Marker','square','LineWidth',5,'Color',[0 0 1]);
set(plot2(3),'Marker','+','Color',[0 0.450980392156863 0.741176470588235]);
set(plot2(4),'Marker','v','Color',[0 0 1]);

% Create xlabel
xlabel('zetaCongr','FontName','Constantia');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-3.35018561306742 4.30748222776595]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Constantia','FontSize',16);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','best');

