function [s] = MLTM_congruent_scatter1(X1, Y1, S1, C1)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 17-Jan-2019 15:00:32

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Low','MarkerSize',15,'Marker','o','LineWidth',3,...
    'LineStyle','none',...
    'Color',[1 0 0]);

% Create plot
plot(X2,Y2,'DisplayName','High','MarkerSize',15,'Marker','+','LineWidth',3,...
    'LineStyle','none',...
    'Color',[0 1 1]);

% Create xlabel
xlabel('zetaCongr','FontName','Constantia');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-3.31733181903839 4.27462843373692]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Constantia','FontSize',16);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','best');

% Create ylabel
ylabel('Arbitration');

